PRECEDES = "p"
MEETS = "m"
OVERLAPS = "o"
FINISHED_BY = "F"
CONTAINS = "D"
STARTS = "s"
EQUALS = "e"
STARTED_BY = "S"
DURING = "d"
FINISHES = "f"
OVERLAPPED_BY = "O"
MET_BY = "M"
PRECEDED_BY = "P"

UNBORN = 0
ALIVE = 1
DEAD = 2

ALLEN_RELATIONS = [
    PRECEDES,
    MEETS,
    OVERLAPS,
    FINISHED_BY,
    CONTAINS,
    STARTS,
    EQUALS,
    STARTED_BY,
    DURING,
    FINISHES,
    OVERLAPPED_BY,
    MET_BY,
    PRECEDED_BY,
]

UNIFORM_DISTRIBUTION = {rel: 1 / 13 for rel in ALLEN_RELATIONS}

FERNANDO_VOGEL_DISTRIBUTION = {}
for rel in ALLEN_RELATIONS:
    if rel in [PRECEDES, PRECEDED_BY, DURING, CONTAINS, OVERLAPS, OVERLAPPED_BY]:
        FERNANDO_VOGEL_DISTRIBUTION[rel] = 1 / 6
    else:
        FERNANDO_VOGEL_DISTRIBUTION[rel] = 0

SULIMAN_DISTRIBUTION = {}
for rel in ALLEN_RELATIONS:
    if rel in [EQUALS, PRECEDES, PRECEDED_BY, STARTS, STARTED_BY, MEETS, MET_BY]:
        SULIMAN_DISTRIBUTION[rel] = 1 / 9
    else:
        SULIMAN_DISTRIBUTION[rel] = 1 / 27
